version: '3.8'

services:
  # Backend - Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: life-sim-backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///game.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-me}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend:/app
      - backend-data:/app
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Frontend - React + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: life-sim-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  backend-data:
